services:
  app:
    build: .
    command: gunicorn -b 0.0.0.0:5000 src.webhook_handler:app --workers=2
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    restart: unless-stopped